services:
  product:
    # Using the latest container
    image: inetsoftware/i-net-helpdesk:latest-with-fonts
    command:
      # The following command will make sure, that the database server
      # is up and running before the actual helpdesk service is run.
      - sh
      - wait-for.sh
      - mariadb:3306
      - --
      - sh
      - ./startServer.sh
      - -Dclearreports.config=User/Default
      - -Dsetupautoexecution=true
    container_name: i-net-helpdesk
    restart: always
    depends_on:
      - mariadb
    ports:
      # There is nothing else on the server, we can use the default webserver ports.
      - 80:80
      - 443:443
    environment:
      # Enable system authentication, so users can register
      # IMPORTANT: the first user will gain administrative permissions!
      CONF_authentication__settings: '[{"minimumPasswordLength"\:"8","minimumPasswordStrength"\:"weak","userCanRegister"\:"true","provider"\:"product"}]'
      # The database settings are tuned to the mariadb settings below.
      CONF_dbsConfigs: '[{"status":"Unknown","dbName":"HDS","url":"jdbc:mariadb://mariadb:3306/inetHDOfficial?useSSL=false&allowPublicKeyRetrieval=true","user":"root","encodedPassword":"AU1KQVA=","host":"mariadb","port":"3306","sid":"","catalog":"inetHDOfficial","driver":"mariadb"}]'
      # prepare default ports
      CONF_listener__port: "80"
      CONF_listener__ssl__port: "443"
      # Enable logging to the docker logs
      CONF_log__engine: "true"
      CONF_log__file: /home/helpdesk/helpdesk.log
      # The backup directory is an extra setting, which is nice, not required.
      CONF_BackupLocation: /home/helpdesk/backup
      # Using the FORCE_IMPORT_CONFIG=0 we ensure that an existing configuration will be re-used upon restart
      # Since we have the persistences mounted into the base system, this makes sense
      FORCE_IMPORT_CONFIG: "0"
    volumes:
      - /srv/i-net-helpdesk/persistence:/home/helpdesk
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  mariadb:
    image: mariadb:8
    environment:
      # Prepare database. Since the database is only accessible as sidecar container
      # we can use simple passwords here. Otherwise the passwords will have to be adjusted
      # in the CONF_dbsConfig environment variable above
      MARIADB_DATABASE: inetHDOfficial
      MARIADB_PASSWORD: inet
      MARIADB_ROOT_PASSWORD: inet
      MARIADB_USER: inetHDOfficial
    restart: always
    volumes:
      - /srv/i-net-helpdesk/mariadb:/var/lib/mariadb
