services:
  product:
    extends:
      file: ./docker-compose.yml
      service: product
    depends_on:
      - strongswan
    networks:
      vpn_bridge:
        ipv4_address: ${IP_END_POINT:-172.172.0.2}

  mysql:
    extends:
      file: ./docker-compose.yml
      service: mysql

  strongswan:
    image: i-net-software/strongswan
    build: ./strongswan
    volumes:
      - /srv/strongswan/ipsec.conf:/etc/ipsec.conf:ro
      - /srv/strongswan/ipsec.secrets:/etc/ipsec.secrets:ro
      - /srv/strongswan/strongswan.conf:/etc/strongswan.conf:ro
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      vpn_bridge:

networks:
  vpn_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: ${IP_SUB_NET:-172.172.0.0/24}
